/* This file is autogenerated from Version.h.in */

#define RUBYCOCOA_VERSION_BARE 1.0.0
#define RUBYCOCOA_VERSION_SHORT 1.0.0
#define RUBYCOCOA_VERSION       "1.0.0"
#define RUBYCOCOA_RELEASE_DATE  "2009-07-24"
#define RUBYCOCOA_SVN_REVISION  "2241"
